export class SRSDetails {
    SRSid:string;
    employeeid:string;
    input:string;
    output:string;
    user:string;
    userstory:string;
    objective:string;
    SBAcomment1:string;
    PMcomment1:string;
    systemspecification:string;
    networkrequirement:string;
    technicalrequirement:string;
    additionalnote:string;
    securitylevelspecification:string;
    SBAcomment2:string;
    PMcomment2:string;
    longsentence:number;
    uncertain:number;
    state:string;
}
